#!/bin/sh

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/dimension.sh" # Loads all defined colors

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=30        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 y_offset=5 \
                 margin=10 \
                 corner_radius=$RADIUS \
                 border_width=0 \
                 border_color=$TRANS \
                 color=$TRANS

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:13.0"  \
                     icon.color=$BAR_COLOR                 \
                     label.font="SF Pro:Semibold:13.0" \
                     label.color=$BAR_COLOR                \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=$RADIUS            \
                     background.height=$BG_HEIGHT        \
                     background.border_width=0 \
                     background.border_color=$BORDER_COLOR \
                     padding_left=4                        \
                     padding_right=4                       \
                     label.padding_left=4                  \
                     label.padding_right=10                \
                     icon.padding_left=10                  \
                     icon.padding_right=4

# --- Left Side Items --

source $ITEM_DIR/front_app.sh
source $ITEM_DIR/aerospace.sh

# -- Center Items

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/media.sh

# --- Right Side Items ---

source $ITEM_DIR/net.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/cpu.sh

# --- Bracket ---

# --- Left

sketchybar --add bracket left_pannel front_app '/space\..*/' \
           --set         left_pannel background.color=$BAR_COLOR \
                                background.corner_radius=$RADIUS  \
                                background.border_width=1 \
                                background.border_color=$BLACK \
                                background.height=$BRACKET_HEIGHT

# --- center

sketchybar --add bracket center_pannel calendar media \
           --set         center_pannel background.color=$BAR_COLOR \
                                background.corner_radius=$RADIUS  \
                                background.border_width=1 \
                                background.border_color=$BLACK \
                                background.height=$BRACKET_HEIGHT

# --- Right

sketchybar --add bracket right_pannel net battery volume cpu \
           --set         right_pannel background.color=$BAR_COLOR \
                                background.corner_radius=$RADIUS \
                                background.border_width=1 \
                                background.border_color=$BLACK \
                                background.height=$BRACKET_HEIGHT


##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
